apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "evolytes.fullname" . }}
  labels:
    {{- include "evolytes.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "evolytes.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "evolytes.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "evolytes.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- if .Values.probes }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path | default "/" | quote }}
              port: {{ .Values.probes.port | default "http" }}
              scheme: {{ .Values.probes.scheme | default "HTTP" }}
              {{- with .Values.probes.headers }}
              httpHeaders:
              {{- toYaml . | nindent 14 }}
              {{- end }}
            initialDelaySeconds: 5
            failureThreshold: 1
            successThreshold: 1
            timeoutSeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path | default "/" | quote }}
              port: {{ .Values.probes.port | default "http" }}
              scheme: {{ .Values.probes.scheme | default "HTTP" }}
              {{- with .Values.probes.headers }}
              httpHeaders:
              {{- toYaml . | nindent 14 }}
              {{- end }}
            initialDelaySeconds: 5
            failureThreshold: 1
            successThreshold: 1
            timeoutSeconds: 5
            periodSeconds: 10
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
